showNewVersionIcon: true
hideAfterStartup: true
randomControllerPort: true
runTimeFormat: "hh : mm : ss"
trayOrders:
  - - icon
  - - status
    - traffic
    - text
hideTrayIcon: false
connShowProcess: true
showTrayProxyDelayIndicator: true
editor: 1
theme: 1
shortcutGlobalMode: ""
editProfileWithCFWEditor: false
bypassText: |
  bypass:
    - login.ecnu.edu.cn
    - frp.kongkong.one
    - localhost
    - 127.*
    - 10.*
    - 172.16.*
    - 172.17.*
    - 172.18.*
    - 172.19.*
    - 172.20.*
    - 172.21.*
    - 172.22.*
    - 172.23.*
    - 172.24.*
    - 172.25.*
    - 172.26.*
    - 172.27.*
    - 172.28.*
    - 172.29.*
    - 172.30.*
    - 172.31.*
    - 192.168.*
    - <local>
mixinText: |-
  mixin: # object
      dns:
          enable: true
          enhanced-mode: redir-host # 或 fake-ip
          listen: 0.0.0.0:53
          nameserver:
              - 223.5.5.5
              - 114.114.114.114
specifyHttpProxyProtocol: false
